apiVersion: v1
kind: Service
metadata:
  name: httpbin
  labels:
    app: httpbin
    service: httpbin
spec:
  ports:
  - name: http
    port: 8000 # kpt-set: ${httpbin-port}
    targetPort: 80
  selector:
    app: httpbin
